# Site settings
title: Regev Golan
description: About Me
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Regev Golan
user_description: I am a senior software engineer who loves his work. <br/>Devoted to developing Big Data, Infrastructure, DevOps and whatever it takes to get the job <b>done</b>.
user_title: Software Engineer
email: look4regev@gmail.com
# twitter_username: lorem_ipsum
github_username:  look4regev
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
